steps:
  - name: build-and-push
    image: quay.io/thegeeklab/wp-docker-buildx
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/shadinmd/scrip-backend
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      containerfile: Dockerfile
      tags:
        - ${CI_COMMIT_SHA}
    when:
      event:
        - push
        - manual
      branch:
        - main
        - stable
      path:
        exclude:
          - k8s/**

  - name: update-manifest-dev
    image: alpine/git
    environment:
      GIT_TOKEN:
        from_secret: docker_password
    commands:
      - "git config --global user.email ci@scrip-backend.local"
      - "git config --global user.name ci-bot"
      - "sed -i 's|image: ghcr.io/shadinmd/scrip-backend:.*|image: ghcr.io/shadinmd/scrip-backend:${CI_COMMIT_SHA}|' k8s/dev/deployment.yaml"
      - "git commit -am 'dev: update image to ${CI_COMMIT_SHA}' || echo 'no changes'"
      - "git push https://$${GIT_TOKEN}@github.com/shadinmd/scrip.git HEAD:${CI_COMMIT_BRANCH}"
    when:
      event:
        - push
        - manual
      branch:
        - main
      path:
        exclude:
          - k8s/**

  - name: update-manifest-prod
    image: alpine/git
    environment:
      GIT_TOKEN:
        from_secret: docker_password
    commands:
      - "git config --global user.email ci@scrip-backend.local"
      - "git config --global user.name ci-bot"
      - "sed -i 's|image: ghcr.io/shadinmd/scrip-backend:.*|image: ghcr.io/shadinmd/scrip-backend:${CI_COMMIT_SHA}|' k8s/prod/deployment.yaml"
      - "git commit -am 'prod: update image to ${CI_COMMIT_SHA}' || echo 'no changes'"
      - "git push https://$${GIT_TOKEN}@github.com/shadinmd/scrip.git HEAD:${CI_COMMIT_BRANCH}"
    when:
      event:
        - push
        - manual
      branch:
        - stable
      path:
        exclude:
          - k8s/**
